ci:
  autofix_prs: true
  autoupdate_schedule: quarterly

repos:

- repo: https://github.com/keewis/blackdoc
  rev: v0.3.9
  hooks:
  - id: blackdoc
    files: '\.py$'

- repo: https://github.com/pycqa/isort
  rev: 5.13.2
  hooks:
  - id: isort
    args: [
    "--profile", "black",
    "--force-sort-within-sections",
    "--skip-glob", "*__init__.py",
    ]

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.5.0
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
      exclude: ^(doc/|tests)
    - id: ruff-format

- repo: https://github.com/keewis/blackdoc
  rev: v0.3.9
  hooks:
  - id: blackdoc
    files: '\.py$'

- repo: https://github.com/codespell-project/codespell
  rev: v2.3.0
  hooks:
  - id: codespell
    additional_dependencies:
      - tomli

- repo: https://github.com/pycqa/pydocstyle
  rev: 6.3.0
  hooks:
  - id: pydocstyle
    additional_dependencies: [toml]
    exclude: "tests/"

- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v18.1.8
  hooks:
  - id: clang-format
    files: |
      (?x)^(
        mapdl_archive/cython/[^_].*\.c.*
      )$

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.10.1
  hooks:
  - id: mypy
    exclude: ^(doc/|tests)
    additional_dependencies: [
    "mypy-extensions==1.0.0",
    "toml==0.10.2",
    "numpy",
  ]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-merge-conflict
  - id: debug-statements
  - id: trailing-whitespace
    exclude: '.*\.(cdb|rst|dat)$'

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.28.6
  hooks:
    - id: check-github-workflows
